### ISSUE TITLE
Where are style-tags and script-tags Snippets Generated?

### ISSUE THREAD

**Issue by kevmon** [Shopify/starter-theme#103]
Hi,

I don't see either style-tags.liquid or script-tags.liquid in /src/snippets.  How can I modify these files?

Thanks in advance

**Comment by t-kelly** [comment]
Hey @kevmon -- the templates for these files are located in [slate-tools](https://github.com/Shopify/slate/tree/master/packages/slate-tools), more particularly: 
- [script-tags.html](https://github.com/Shopify/slate/blob/master/packages/slate-tools/tools/webpack/script-tags.html)
- [style-tags.html](https://github.com/Shopify/slate/blob/master/packages/slate-tools/tools/webpack/style-tags.html)
