### ISSUE TITLE
styles are not loaded on mobile browser

### ISSUE THREAD

**Issue by amritsub** [Shopify/starter-theme#108]
I am developing a theme using the starter-theme as a starting point. My theme's css changes that I have made show up fine on my desktop browser(Google Chrome), but when I visit my store on my mobile browser, none of the CSS gets applied and the site looks unstyled. Does anyone know why this might be happening?

**Comment by amritsub** [comment]
Thanks for your quick reply @t-kelly! `yarn deploy` solved my issue. I just looked at the docs under Local Development and looks the information is there, I just didn't know where to look before.
```
Developers wanting to share an instance of their store with other developers are often confused when they see their store appear broken. Because CSS and JavaScript are being served locally, your theme won’t function on any machine other than the one the Express server is currently running on.
```

**Comment by huguestennier** [comment]
Gonna close this for now - but we're working towards improving this portion of the docs for less confusion.
