### ISSUE TITLE
No grid.scss? 

### ISSUE THREAD

**Issue by SaroGFX** [Shopify/starter-theme#118]
Hello, 

I am very new with Slate and the Starter Theme, and GitHub for that matter, so I might be asking a dumb question. But I can't seem to find the grid.sccs when I build a new Starter Theme? On the V0 site (https://shopify.github.io/slate/css-examples/) there is mention of Neat Grid being imported. 

But I can't find the Neat Grid css back in the folder, and also the classes do not work. However, there are grid variables in variables.scss, so I was wondering if I am missing something? 

Thanks for clearing that up.

**Comment by huguestennier** [comment]
Starter theme is based on Slate v1 - which is still in beta, but you can find the [documentation here](https://github.com/Shopify/slate/wiki).

We try to keep Starter theme as light as possible with only minimum styling or classes so there's no grid framework imported.
