### ISSUE TITLE
Importing sections/product.js into theme.js

### ISSUE THREAD

**Issue by jonathanmoore** [Shopify/starter-theme#12]
### Problem

Currently it is unclear how the section or template files could be imported and used in theme.js.

**Comment by t-kelly** [comment]
This is something that is considered a work and progress. I will blame the current state of `product.js` on being an `alpha` release 😅

**Comment by pveen2** [comment]
How can we get product.js working on slate? So the variant chanes are working?

**Comment by itmustbe** [comment]
I would love to know the answer to this too!  I'm trying to figure it out myself... but it'd be so cool if it "just worked" out-of-the-box, and then you could customize it, make changes, write it to suit your own project, etc., but all from a starting point of seeing it work to begin with ;)

**Comment by tomhirst** [comment]
`sections/product.js` is actually unusable in its current format. The imports for `Variants`, `images` and `currency` are currently missing too.

I guess we need to revert back to the previous version of Slate for JS...

**Comment by t-kelly** [comment]
Ladies and gentlemen, please may I refer to my initial comment:
> This is something that is considered a work in progress. I will blame the current state of product.js on being an alpha release 😅

You are more then welcome to open a PR in the meantime!
