### ISSUE TITLE
Assets are not loaded properly

### ISSUE THREAD

**Issue by liron-navon** [Shopify/starter-theme#130]
### Problem

I installed slate and started a new project from shopify/starter-theme, It seems that nither the css or the javascript files are imported properly.
I did set up the certificate as the instructions show, but it still does that.

### Replication steps

```
$ npx create-slate-theme my-theme shopify/starter-theme
$ cd my-theme # change the config in .env file.
$ npm start
```

### More Information

slate-tools version: 1.0.0-beta.14
node version: v10.11.0
npm version: 6.5.0

before setting the certificate I got a warning on the URL box in chrome telling me the connection is not secure, after setting up the certificate the warning disappeared, so I guess the certificate is not to blame for this.

<img width="725" alt="screen shot 2018-12-11 at 16 32 58" src="https://user-images.githubusercontent.com/18119833/49811239-20e0e780-fd63-11e8-9046-47af24f6f15b.png">

**Comment by km-likhon** [comment]
i need help with self-signed-SSL-certificate
https://github.com/Shopify/slate/wiki/4.-Create-a-self-signed-SSL-certificate
this is work on macOs but i tired on windows.
can any one help me how to create self-signed-SSL-certificate on windows for slate v1 theme
