### ISSUE TITLE
Not able to find footer code

### ISSUE THREAD

**Issue by dhavalwd** [Shopify/starter-theme#132]
Hello,

This is my first time theming for Shopify theme so forgive me if I ask really simple question. I am trying to edit the code for footer in this theme. As `footer` is a section, I am editing `/src/section/footer.liquid` but my change doesn't appear on the page.

Am I editing wrong file?

Here is the link: https://dhaval-demo-3.myshopify.com/
Password: demo3-dhaval

Best,
Dhaval

**Comment by dhavalwd** [comment]
So, I realized that there was a different code in `/src/section/footer.liquid` file than what I had locally. I tried to use `Theme download` command but it didn't work. So, I manually copied file locally and then updated my code and then ran `npm run deploy` and it worked. It pushed my changes to the store site.

If this is not the correct way to do it or if there is a better way to do it, please let me know.

Thanks.

**Comment by huguestennier** [comment]
👋 first question, when developing, are you running `yarn start` without any errors in the terminal?

**Comment by dhavalwd** [comment]
Hey 👋 I am using `npm run start` and yes, it runs without any errors.

**Comment by huguestennier** [comment]
If you `npm run start` and save your `footer.liquid` file, in your terminal you should see it being uploaded to your Shopify store. You would only need to refresh the page to see the changes.

**Comment by dhavalwd** [comment]
Unfortunately, that wasn't the case. I was running `start` command and then I made some changes in my file. But it never updates it on the site. I had to copy code from "Theme Editor" from "Admin" screen and paste it locally to `Footer.liquid` file and then make changes into it get it working. Not sure if I am doing anything wrong.

**Comment by huguestennier** [comment]
What do you see in your terminal when you update a liquid file?

**Comment by dhavalwd** [comment]
Sorry for the delayed response on this. Happy New year btw. I think I resolved the issue. I don't have all the files on my local workspace so I would have to download those files and then upload it to get it working. Everything is working fine now and thanks for your help. :)
