### ISSUE TITLE
drop jquery dependency in login.js

### ISSUE THREAD

**Issue by isaac-martin** [Shopify/starter-theme#138]
#122 Makes some great changes to the theme addresses, and also removes jQuery. I'm not sure if dropping jQuery support is a Long Term Goal of this repo?

The login and addresses functionality are so tied together so if given the go ahead I'd like to remove the jquery dependency that relates to the `login.js` and subsequently `login.liquid`

From my understanding once this PR request is merged there is just `jquery` left in `product.js` an `gift_card.js` which I am also happy to tackle down the line.

I know this also makes no difference if someone installs an App that has jquery as a dependency, but would maybe be nice to give the shopify/slate community the ability to not have to use it if they don't want to.

**Comment by huguestennier** [comment]
Removing jQuery as a dependency is definitely a goal. Feel free to open a PR and we'll review it!
