### ISSUE TITLE
Starter Theme + ThemeKit on a Windows machine

### ISSUE THREAD

**Issue by gomarion** [Shopify/starter-theme#144]
Good day!

I'm quite new to Shopify Theme development and I'm trying to look for a starter theme to build my first theme. Is it possible to use this starter theme by cloning it, then use ThemeKit to push my changes to the development store instead of Slate? I'm asking this because I read that Slate is not yet recommended to be used in Windows. Thanks a lot in advance!

**Comment by t-kelly** [comment]
Hey @gomarion -- Out of the box, Starter Theme only works with Slate. You're welcome to fork the repo and adjust it to your own build setup that uses ThemeKit.
