### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by mikehwagz** [Shopify/starter-theme#148]
I've added additional styles to `styles/theme.scss` and upon page load (as well as when navigating throughout the site), I am seeing a quick flash of completely unstyled HTML as if the CSS were loaded in asynchronously.

I am an experienced WordPress developer with virtually no Shopify experience, so please excuse my ignorance if this is expected behavior.

**Comment by t-kelly** [comment]
hey @mikehwagz -- this is expected behaviour only seen in dev builds (yarn start), and is due to [style-loader](https://github.com/webpack-contrib/style-loader) injecting styles with JS to enable [hot module reloading](https://github.com/webpack-contrib/style-loader#options).

**Comment by jetlej** [comment]
This is happening for me in production as well.

**Comment by jasecoop** [comment]
Run `yarn deploy` and visit the theme preview URL found in Shopify's dashboard.

I was having this problem in the URL provided by `yarn start`, I assumed it _was_ production but it seems that it isn't.

**Comment by garrettboatman** [comment]
Not sure this should be closed @t-kelly.
Getting this on `yarn deploy` as well. For the life of me, I can't determine what's causing the flash.

Production URL:
https://shop.byteme.com

Performance inspector:
https://www.loom.com/share/98e7d999344e4e33ba75ed5f16fadc6b
