### ISSUE TITLE
Shopify Plus Layouts

### ISSUE THREAD

**Issue by djallits** [Shopify/starter-theme#19]
Should the Shopify Plus layout `checkout.liquid`, or any other Plus related artifacts, be included within the starter theme? For non-Plus stores, the presence of the layout has zero-effect.

**Comment by chrisberthe** [comment]
I'm leaning towards no, despite these being ignored for non-Shopify Plus stores. I think creating a Plus Starter Theme instead would be more reasonable. At least this way we can separate the concerns.

**Comment by djallits** [comment]
I understand your stance, but that is against the DRY principle as the vast majority of the starter theme would be just a duplicate of the base starter theme.

How would you feel about stubbing these files out in an npm package and then publishing them via a CLI command?

**Comment by zomars** [comment]
I would be confused if I saw a `checkout.liquid` template, edit it and not seeing any changes being made as a non Plus user.

**Comment by t-kelly** [comment]
I'm with @chrisberthe on this one. @djallits duplication of solutions/code across multiple theme projects is a separate problem that we need to deal with, with one potential solution eventually being [componentization of theme UI elements](https://github.com/Shopify/slate/issues/336).

**Comment by djallits** [comment]
@t-kelly Thank you. I didn't see this issue before and I am going to close this in favor of #336 as a solution to that issue would satisfy this.
