### ISSUE TITLE
slate.config.js not loading properly

### ISSUE THREAD

**Issue by niedfelj** [Shopify/starter-theme#48]
In trying to override/extend some settings in my slate.config.js, I noticed that the settings weren't taking. It seems like it needs to be nested under slateTools based on the way the schema crawls the configs? Not sure which project to submit this to?

```
module.exports = {
  slateTools: {
    extends: {
      dev: {resolve: {alias}, output: {library: 'Wardrobe', jsonpFunction: 'webpackJsonpWardrobe'}},
      prod: {resolve: {alias}, output: {library: 'Wardrobe', jsonpFunction: 'webpackJsonpWardrobe'}},
    },
  }
};
```

**Comment by t-kelly** [comment]
Fixed in https://github.com/Shopify/starter-theme/commit/23f14812ebedd49490632f2f3cdb805add4cd388
