### ISSUE TITLE
HTML validation: Duplicate attribute "ID" search box

### ISSUE THREAD

**Issue by tauthomas01** [Shopify/starter-theme#57]
### Problem

* In the search result page, the W3C validator complains about the search textfield having the same ID value called `Search` in the source code

[![alt](http://take.ms/frBLq)](http://take.ms/frBLq)

### Solution
* Change the "ID" value of the search input to something different (will it break the functionality?)

### Video
[Video showing the source code](http://take.ms/3lq8h)

Pings here:
@t-kelly @NathanPJF @chrisberthe

**Comment by JahidulOfficial** [comment]
No. it doesn't

**Comment by tauthomas01** [comment]
https://github.com/Shopify/starter-theme/blob/8addc17a400298e90572e76a99d5784e90db83c8/src/templates/search.liquid#L19-L23

https://github.com/Shopify/starter-theme/blob/8addc17a400298e90572e76a99d5784e90db83c8/src/sections/header.liquid#L87-L91

These are the original source files where it's outputting the markup.
