### ISSUE TITLE
Demonstrate how to use fonts and the `assets/fonts/` folder

### ISSUE THREAD

**Issue by zomars** [Shopify/starter-theme#59]
Also there's mention of the folder in the docs, but it is ignored by Slate.

**Comment by niedfelj** [comment]
Fonts AND Images. Seems like the slate-tools only builds/uploads what is in the static folder, maybe these should just go under there?

**Comment by t-kelly** [comment]
Fonts need to be referenced like an image (relative URL) in a Liquid file for them to be included in the dependency tree and copied to `dist`.

Renaming this issue because we clearly need an example somewhere!

**Comment by t-kelly** [comment]
This directory no longer exists. Please see [release notes for Slate v1.0.0-beta.12](https://github.com/Shopify/slate/releases/tag/v1.0.0-beta.12) for more details.
