### ISSUE TITLE
data-product-single-thumbnail doesn't do anything

### ISSUE THREAD

**Issue by t-kelly** [Shopify/starter-theme#6]
> **data-product-featured-image** changes the featured image when a variant is selected. However **data-product-single-thumbnail** doesn't seem to do anything. 
>
> Possible uses when the data-product-single-thumbnail get's clicked could be:
> - Change the featured image
> - Change the selected variant
>
> Or am I missing something?

Copied from https://github.com/Shopify/slate/issues/327

**Comment by tauthomas01** [comment]
The overall functionality is implemented by this PR: https://github.com/Shopify/starter-theme/pull/80

The next task would be adding the same behavior when you click on the thumbnails to show the variant price and availability.
