### ISSUE TITLE
Featured product section is not loading product.js

### ISSUE THREAD

**Issue by montalvomiguelo** [Shopify/starter-theme#64]
The `featured-product.liquid` section depends on `assets/scripts/sections/product.js` in order to work, but it is not being loaded.

In `assets/scripts/templates/product.js` the script of product section is loaded like so:

```js
import '../sections/product';

import $ from 'jquery';
import sections from '@shopify/theme-sections';

$(document).ready(() => {
  sections.load('product');
});
```

If we load `product.js` in `theme.js` it will be duplicated in `layout.theme.js` and `template.product.js`

```diff
+ import '../sections/product';

+ import sections from '@shopify/theme-sections';

window.slate = window.slate || {};
window.theme = window.theme || {};

$(document).ready(() => {
+  sections.load('product');

```

What is the way to go?

**Comment by montalvomiguelo** [comment]
I have created this file *src/assets/scripts/templates/index.js*.

Example: loading scripts for the featured-product section (product.js) in index template

```js
import '../sections/product';

import $ from 'jquery';
import sections from '@shopify/theme-sections';

$(document).ready(() => {
  sections.load([
  	'product',
  ]);
});
```

Now featured product section works

**Comment by t-kelly** [comment]
> So to get the featured-product section working properly in home page, we only need to add the src/assets/scripts/templates/index.js file

Exactly.

**Comment by montalvomiguelo** [comment]
sure :)
