### ISSUE TITLE
Errors in slate.config.js cause file to just be ignored

### ISSUE THREAD

**Issue by niedfelj** [Shopify/starter-theme#65]
I edited my slate.config.js because I wanted to put in an output library and jsonpFunction name (which I think would be a good idea for the slate project too (webpack changed the jsonpfunction to an array in the latest versions), so it doesn't collide with other apps that using webpack (ie Flow checkout, although they have since added this to their config also). I forgot a comma separating the properties, and then yarn build was throwing an error stating css variables didn't exist. I didn't dig into it, but it was resolved by fixing the slate.config.js. This should throw an error if it can't be parse.

```
/* eslint-disable no-undef */

const path = require('path');

const alias = {
  jquery: path.resolve('./node_modules/jquery'),
  'lodash-es': path.resolve('./node_modules/lodash-es'),
};

module.exports = {
  slateCssVarLoader: {
    cssVarLoaderLiquidPath: ['src/snippets/css-variables.liquid'],
  },
  slateTools: {
    extends: {
      dev: {
        resolve: {alias}
        output: {library: 'Wardrobe', jsonpFunction: 'webpackJsonpWardrobe'}
      },
      prod: {
        resolve: {alias}
        output: {library: 'Wardrobe', jsonpFunction: 'webpackJsonpWardrobe'}
      },
    },
  },
};
```

**Comment by t-kelly** [comment]
Fixed in https://github.com/Shopify/slate/pull/750
