### ISSUE TITLE
Featured Image for Product (data attributes missing)

### ISSUE THREAD

**Issue by el-rotny** [Shopify/starter-theme#68]
This looks like an oversight of some changes related to alpha. 

Change in product.liquid that now  calls a snippet instead of the image directly in the section to render the featured product has removed some data attributes that might need to be available so that we keep the ability to select and swap images - functionality that I imagine was intended to be kept from slate and debut.

**Change:**
https://github.com/Shopify/starter-theme/pull/16/files#diff-b3fff31a00a3b2a50049d8c63c244545R17

**Now merged:**
https://github.com/Shopify/starter-theme/blob/master/src/sections/product.liquid#L13

**What product.js wants:**
`productFeaturedImage: '[data-product-featured-image]',`

**As in the following:**

 `product.js`
```
const selectors = {
    ...
   productFeaturedImage: '[data-product-featured-image]',
   ...
}
...
this.$featuredImage = $(selectors.productFeaturedImage, this.$container);
...
if (this.$featuredImage.length > 0) {
      this.settings.imageSize = imageSize(this.$featuredImage.attr('src'));
      preload(this.productSingleObject.images, this.settings.imageSize);

      this.$container.on(
        `variantImageChange${this.namespace}`,
        this.updateProductImage.bind(this),
      );
    }
```

Sniffed the snippet to see if there was a fallback but none available.
https://github.com/Shopify/starter-theme/blob/master/src/snippets/responsive-image.liquid#L58

Will note that Im in an active project and cant fully test this out with variants but this will obviously fail to allow since `this.$featuredImage.length > 0` is pretty explicit.

**Comment by t-kelly** [comment]
Thanks @el-rotny!
