### ISSUE TITLE
Explain the lack of styles

### ISSUE THREAD

**Issue by t-kelly** [Shopify/starter-theme#7]
There is some confusion as to why Starter Theme comes (mostly) unstyled. In Slate v0, we had a page in the docs called [Intentially Blank](https://shopify.github.io/slate/theme/#intentionally-blank) -- we should have the equivalent of this in the Starter Theme docs.

Related: https://github.com/Shopify/slate/issues/419

**Comment by chrisberthe** [comment]
Updated in a949a2e7fb02a5818a9f6e5e3d77225613601d91.
