### ISSUE TITLE
Demo of starter theme

### ISSUE THREAD

**Issue by daveshawsa** [Shopify/starter-theme#76]
Is there a demo of the starter theme?

I'm aware the documentation says that the theme should appear 'broken' but I've had differing results after deploying with Slate and as there's nothing to compare to it's not possible to tell whether it's been successful or whether there has been compiling or other config errors.

Thanks,
Dave

**Comment by chrisberthe** [comment]
Hi @daveshawsa, currently there isn't any. You can usually tell if something is wrong based on the output from the terminal (after running a deploy), and the dev tools console (once it launches).

If there aren't any errors being outputted, I think it's safe to assume everything is working as expected. But we could definitely think up ways in which we can reassure the user that what they see is in fact what it's supposed to be.
