### ISSUE TITLE
Integrating Turbolinks into Slate

### ISSUE THREAD

**Issue by darkrubyist** [Shopify/starter-theme#89]
Hello there,

I was wondering what do you think about integrating Turbolinks into Slate Themes.
Is there a way to make it fully compatible with Slate Js code and also Shopify Apps integrations?

I'm sure Turbolinks can give an amazing power into a Shopify Theme, but I wanted to hear your opinions about it.

Cheers

**Comment by t-kelly** [comment]
@darkrubyist It's not at the top of our todo list, but you should try [making your own starter theme](https://github.com/Shopify/slate/wiki/How-to-create-your-own-Starter-Theme) and give it a crack! Would love to hear how it goes and what any blockers you encounter.
