### ISSUE TITLE
Add our preferred solution to responsive images 

### ISSUE THREAD

**Issue by t-kelly** [Shopify/starter-theme#9]
Followup to https://github.com/Shopify/starter-theme/issues/8

Along with Standard Sections, all themes in the Theme Store will be required to use responsive images. Responsive images have a huge effect on overall user experience, so it's a no brainer that we would want them in any future theme project.

All of our free themes are now using responsive images, with additional functionality provided by [Lazysizes](https://github.com/aFarkas/lazysizes). Let's include this solution in Starter Theme so that our future projects can get up and running even faster.

[More details here](https://docs.google.com/document/d/1-ptW0oROKZ0a930QGDJf7smsMzJV6w0EjOeER3amzYY/edit?pli=1#heading=h.cbgko5k2z9fg)

**Comment by jeremystephencobb** [comment]
Potentially related issue: https://github.com/Shopify/brooklyn/issues/210

When the same image is featured twice on one page (if it is in two featured collections) the styling from one will override the other.
